apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schema-registry
  name: my-cluster-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - image: apicurio/apicurio-registry-mem:2.0.0.Final
          name: schema-registry
          resources:
            limits:
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: schema-registry
  name: my-cluster-schema-registry-api
spec:
  selector:
    app: schema-registry
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
